### ISSUE TITLE
please change condition if ($UHS -ne "null")

### ISSUE THREAD

**Issue by MadhuSunke417** [jbasuroy369/Install-UpdateHealthTools#1]
$UHS = Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -match “Microsoft Update Health Tools”}
if ($UHS -ne "null")
{
Write-Log "Update Health Tool already exist on this device"
}

please change the if condition to properly check for Null value 

change $UHS -ne "null" to -not[string]::IsNullOrEmpty($UHS)

**Comment by jbasuroy369** [comment]
Appreciate your time and effort to go through the script and help correct it. Thanks 👍
